const About=()=>{
    return(
        <>
        <div>
            <p>ganga</p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin varius diam sit amet ex maximus efficitur eu sit amet libero. Proin sollicitudin cursus consequat. Duis tempor maximus imperdiet. Donec non turpis quis mauris imperdiet imperdiet. Nulla id urna sit amet lacus congue aliquam et non ligula. Maecenas nec mi et ante suscipit vulputate. Donec congue enim quis rhoncus tristique. Sed justo erat, feugiat a efficitur vitae, iaculis nec ipsum.

Fusce vitae felis quis velit pulvinar consequat quis in libero. Curabitur nulla nulla, varius et varius dignissim, mollis a libero. Curabitur id turpis vitae justo bibendum blandit ut in ante. Duis lobortis neque ut faucibus vehicula. Quisque bibendum faucibus efficitur. Morbi sed cursus justo. Curabitur nisi purus, tempor vitae diam nec, placerat hendrerit turpis.

In hac habitasse platea dictumst. Vestibulum sit amet pellentesque lorem. Nam aliquam, enim eu fermentum euismod, purus mauris sodales sem, nec tempor tellus eros eu massa. Vivamus interdum nunc sed nisi fringilla, ac elementum sem tempus. Sed elementum porttitor bibendum. Maecenas semper quam a augue egestas vestibulum. Nullam eget tempus tellus. Ut porta magna eget rutrum scelerisque. Phasellus aliquet velit eu mi elementum feugiat. Phasellus magna nisl, egestas id nunc a, lobortis auctor eros. Aliquam vitae diam dui.

Vestibulum risus lectus, fermentum nec mauris non, pharetra ultricies urna. Nullam vitae lobortis mauris. Integer sed ligula dignissim, feugiat lectus nec, sollicitudin tortor. Donec porttitor magna eget magna mollis pretium. Duis sed odio sed leo fringilla aliquet sed vitae lectus. Quisque sagittis velit vel justo pharetra, nec viverra enim volutpat. Aenean bibendum risus non fringilla finibus. Cras at sem sed felis tristique dictum.

Sed sed velit in nulla sollicitudin dignissim at ut mi. Pellentesque facilisis varius diam a gravida. Phasellus tempus tincidunt tellus sed pretium. Maecenas iaculis libero et justo ullamcorper, gravida ultricies diam auctor. Maecenas pretium, lectus quis rutrum egestas, lectus turpis malesuada neque, vel consectetur velit tortor mollis mi. Donec iaculis accumsan arcu vitae porttitor. Donec at ipsum maximus, hendrerit libero in, iaculis lectus. Nunc a vulputate neque, sed tristique elit. Sed vel purus at risus sagittis eleifend vitae ac tellus. Vivamus purus purus, sodales sit amet nisl vel, convallis porttitor tellus. Duis ornare magna eu ipsum ullamcorper, ut lobortis urna finibus. Quisque pretium ante et ex auctor blandit. Quisque euismod ipsum et pellentesque tempus. Nulla et volutpat odio, et convallis arcu. Phasellus a ante vel leo imperdiet rhoncus sit amet a orci.

Etiam rutrum metus orci, eu laoreet felis varius eget. Suspendisse purus libero, efficitur in ultricies ut, lacinia ut felis. Morbi ultricies quis enim sit amet vestibulum. Maecenas id elementum nisl. Etiam eu blandit urna. Quisque semper, tellus in malesuada tincidunt, quam magna convallis eros, eget facilisis orci urna id quam. Fusce vel elit sapien. In bibendum, nibh quis varius vestibulum, neque urna facilisis quam, quis commodo orci ante id risus. Curabitur volutpat mi sed nibh pellentesque placerat quis a metus. Sed facilisis erat diam, eget consequat erat tincidunt ac. Proin accumsan nisi ac arcu pellentesque ultricies. Aenean eget velit mi. Vestibulum suscipit enim interdum est condimentum consectetur. Fusce mauris mauris, euismod eu ligula eu, mattis ornare lorem. Ut egestas nunc vel augue consectetur, id iaculis odio pulvinar.

Pellentesque ullamcorper condimentum felis vitae sollicitudin. Pellentesque tempor, risus vel venenatis tincidunt, purus risus semper neque, in aliquam purus felis nec magna. Donec magna lacus, faucibus quis scelerisque hendrerit, facilisis sed tellus. Pellentesque bibendum suscipit risus, a laoreet odio euismod et. Duis tincidunt urna scelerisque sapien auctor, vel pulvinar nibh fringilla. Integer a sapien convallis mi scelerisque tempus. Sed mollis est nec ligula pharetra suscipit.

Nam enim sapien, efficitur volutpat elit ut, pretium maximus neque. In a nibh sit amet urna varius rutrum vitae id lorem. Quisque eu odio in nibh sagittis auctor nec non risus. Nunc suscipit urna a justo finibus, et dictum enim vulputate. Curabitur et tellus luctus, rhoncus odio ut, placerat dui. Morbi euismod, odio et ultrices sodales, odio massa euismod risus, nec imperdiet mi leo malesuada nibh. Curabitur eu magna vitae arcu scelerisque cursus. Mauris tempor feugiat odio, ut auctor neque varius id. Donec in pellentesque tellus. Mauris a urna arcu. Praesent quam sem, vestibulum vitae elit ac, imperdiet iaculis arcu.

Nullam accumsan nulla et velit cursus, id condimentum nisi rhoncus. Pellentesque eget nulla eu justo consequat posuere sit amet vel sapien. Vivamus tempor erat augue, at rhoncus leo aliquam ac. Mauris sed tortor sed ipsum vehicula aliquet cursus at leo. Suspendisse potenti. Integer a tellus nec elit ornare hendrerit. Proin congue mi nec justo aliquam lobortis. Sed et diam hendrerit, luctus felis vel, eleifend arcu. Nulla auctor gravida nibh, quis mattis ante euismod vel.

Sed vel dictum lectus, ut tincidunt mi. Aliquam vitae auctor augue. Quisque interdum pretium mi, vel fringilla est cursus dictum. Aliquam consectetur, ante eget facilisis dapibus, enim enim efficitur ipsum, quis pulvinar lacus velit sed tortor. Donec et porta erat. Nunc et iaculis tortor. Proin fringilla mauris vel aliquam vulputate. Ut at quam tortor.

Quisque efficitur vitae urna a commodo. In auctor ante ex, ut viverra dolor hendrerit vel. Phasellus efficitur mauris et tincidunt volutpat. Cras quis est massa. Suspendisse ac tortor sodales, accumsan massa a, posuere nunc. Nam dictum, nibh feugiat imperdiet eleifend, ante quam aliquet neque, sit amet posuere arcu quam quis nibh. Aliquam interdum pretium nunc eu eleifend. Vestibulum quis feugiat neque, a vestibulum dolor. Nam vehicula dolor massa, vel luctus nunc varius a. Curabitur gravida tortor pharetra eros tincidunt porttitor. Mauris non purus ante. Etiam aliquet est nec dictum congue.

Praesent consectetur, turpis eu lobortis imperdiet, est augue malesuada justo, non lobortis augue dui at ex. Praesent ut elementum nunc. Aenean at orci sit amet enim vehicula vehicula nec at ligula. Curabitur sed egestas ante. Morbi a magna dapibus velit blandit porta. Maecenas et dui arcu. Aliquam hendrerit elit nisl, quis aliquet justo mollis nec. Phasellus id arcu at felis mattis rhoncus. Sed ac dolor libero. Nam laoreet metus vitae diam mattis laoreet. Maecenas tempus mauris non est tempor, vel porta metus rutrum.

Sed ut lobortis odio, in pellentesque ipsum. Integer sapien nibh, venenatis eget pharetra at, euismod et turpis. Cras tincidunt est et sem pulvinar, condimentum vehicula diam interdum. Nunc vitae rutrum augue. Mauris tortor arcu, varius pulvinar purus at, vulputate scelerisque velit. Duis nec justo mollis, ornare erat id, vestibulum magna. Curabitur scelerisque luctus ante at imperdiet. Quisque molestie tincidunt orci, id volutpat ex. Nulla facilisi. Maecenas tristique efficitur commodo. Donec semper porttitor feugiat. Integer a faucibus nisl. Donec eu lorem non turpis sodales pharetra eu ut justo. Etiam id feugiat augue. Donec nibh dui, lobortis vel libero vel, congue tempor tellus.

Sed hendrerit porttitor odio, sit amet fermentum ex tempor quis. Aliquam erat volutpat. Suspendisse facilisis, est nec imperdiet porta, purus turpis efficitur ex, nec varius sapien risus condimentum tortor. Sed justo ligula, euismod vel posuere at, bibendum sit amet lectus. Fusce consequat nulla malesuada erat pretium rhoncus. Vestibulum iaculis lorem ac diam finibus mattis. Aliquam varius odio in augue tristique, vel finibus diam maximus. Mauris sem lectus, lacinia at blandit sit amet, consequat non est. Mauris pretium leo ut orci convallis elementum.

Etiam a nunc augue. Nam sit amet consectetur nisl, nec luctus justo. Pellentesque vel tincidunt nulla, ut ullamcorper neque. Nunc faucibus luctus nulla, nec luctus magna bibendum in. Proin ac sodales turpis. Pellentesque massa justo, bibendum eleifend semper id, facilisis id quam. Aliquam arcu sem, dictum eget libero id, laoreet cursus purus. Praesent vestibulum lectus vitae ligula consectetur egestas. Nulla facilisi. Aenean tortor risus, commodo ac malesuada eu, maximus sit amet eros. Cras orci ante, viverra sit amet mattis ac, interdum vel ante. Suspendisse enim tellus, dictum et feugiat at, bibendum non dui. Phasellus vel quam tempor, pulvinar sapien id, pulvinar ipsum.

Suspendisse lacinia odio risus, porta iaculis mi commodo ut. Cras ut maximus arcu. Donec maximus turpis vitae consequat suscipit. Aliquam varius felis ante, vel luctus purus finibus quis. Nullam in nisi vel elit hendrerit pellentesque ut id lectus. Duis eu semper orci. Ut ac tellus metus. Maecenas nulla tellus, facilisis quis quam quis, bibendum egestas orci. Vestibulum nec est a odio lobortis tincidunt. Duis consequat purus non nisi pellentesque, in cursus orci viverra. Etiam aliquam interdum urna non auctor.

Ut pellentesque tristique turpis ac laoreet. Cras posuere luctus leo eget ornare. Sed sollicitudin vitae odio eget convallis. Nulla in lacinia turpis. Vivamus a lorem lorem. Nulla et dolor vel ipsum accumsan eleifend vel eget est. Integer placerat viverra dui, ut faucibus tellus luctus sed. Fusce finibus feugiat nibh, sed imperdiet neque venenatis eu. Maecenas aliquet massa et magna dapibus, ut sollicitudin sem iaculis. Vivamus id aliquam libero. Vivamus malesuada, turpis vel gravida condimentum, eros tortor mollis velit, eget pretium justo tellus pretium diam. Proin blandit ultrices justo, vitae mollis arcu feugiat sit amet. Integer porttitor magna at imperdiet posuere.

Aliquam in libero est. Vivamus commodo leo eu tortor iaculis luctus. Integer dolor risus, condimentum nec laoreet in, vehicula vel ante. Integer at sapien nec lectus cursus rutrum. Donec placerat bibendum leo, eu mattis lacus sollicitudin quis. Nulla commodo risus nec velit blandit, id cursus lectus pulvinar. Quisque risus metus, dapibus vitae bibendum sit amet, congue at tellus. Cras molestie, enim quis luctus accumsan, est augue porta odio, vel venenatis odio augue et erat. Morbi ac posuere metus. Nam tincidunt elementum ligula, ac sagittis libero dignissim non.

Donec mauris nisl, gravida eget purus nec, finibus sollicitudin ipsum. Sed dapibus magna semper lorem ultricies, eget lacinia enim imperdiet. Sed sed interdum ligula, ac blandit nulla. Nulla facilisi. Ut scelerisque metus justo, in consectetur est blandit vitae. Suspendisse potenti. Praesent dui metus, ultricies vitae urna sit amet, luctus accumsan magna. Morbi posuere porta ipsum non dignissim. Integer eu aliquam odio. Cras risus quam, fringilla nec commodo ac, gravida a sem.

Nulla convallis cursus odio, auctor iaculis purus. Phasellus venenatis efficitur est, a tempor ex accumsan in. In ornare mi a diam sollicitudin congue. In tincidunt vitae sapien non venenatis. Morbi viverra ex a vehicula ultrices. Maecenas mollis posuere leo, quis porta ligula feugiat sit amet. Integer vel eleifend purus. Aliquam scelerisque nibh arcu, ac porttitor lectus egestas id. Morbi imperdiet pharetra justo, ut egestas tellus ultricies sed. Quisque venenatis ligula nibh, ut sodales leo sagittis at. Morbi lectus mi, lacinia eu maximus ac, aliquam eget diam. Sed lectus libero, porta ac elit sed, commodo hendrerit metus. Praesent auctor tellus justo, quis viverra mauris volutpat vitae. Suspendisse nibh augue, hendrerit id nulla vel, aliquam finibus tortor.
        </div>
        </>
    )
}

export default About;